---
version: "3"
services:
  selenium:
    image: selenium/standalone-chrome@sha256:0d1847a44c5e21df5891426dd1c054d4a3b51d0688791903f809bddd76595e65
  ruby:
    image: ruby:2.5.3
    command: |
      gem install bundler && bundle install && ruby main.rb
    volumes:
      - "./:/app"
    working_dir: /app
    links:
      - selenium
